// scripts/seed.mjs
// One-time script to seed Firestore 'monuments' collection with 20 Indian monuments.
// Usage: node scripts/seed.mjs
//
// Requires: npm install firebase-admin (devDependency)
// Set environment variables or edit the serviceAccount path below.
//
// ─── How to run ────────────────────────────────────────────────────────────────
// 1. Go to Firebase Console → Project Settings → Service Accounts → Generate new private key
// 2. Save the downloaded JSON as scripts/serviceAccountKey.json
// 3. Run: node scripts/seed.mjs

import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore }        from 'firebase-admin/firestore';
import { createRequire }       from 'module';
import { readFileSync, existsSync } from 'fs';
import { fileURLToPath }       from 'url';
import { dirname, join }       from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const keyPath   = join(__dirname, 'serviceAccountKey.json');

if (!existsSync(keyPath)) {
  console.error('❌  serviceAccountKey.json not found at', keyPath);
  console.error('   Download it from Firebase Console → Project Settings → Service Accounts.');
  process.exit(1);
}

const serviceAccount = JSON.parse(readFileSync(keyPath, 'utf8'));
initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();

// ─── 20 Monuments Dataset ──────────────────────────────────────────────────────
const MONUMENTS = [
  {
    id: 'taj-mahal',
    name: 'Taj Mahal',
    city: 'Agra',
    state: 'Uttar Pradesh',
    category: 'Mughal Architecture',
    unescoStatus: true,
    rating: 4.9,
    entryFee: 50,
    openingTime: '06:00 AM',
    closingTime: '06:30 PM',
    year: 1653,
    builtBy: 'Emperor Shah Jahan',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=1200&auto=format&fit=crop',
    description: 'An immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife, Mumtaz Mahal.',
    history: 'Construction of the Taj Mahal began in 1632 CE. Shah Jahan commissioned the grand structure to hold the tomb of Mumtaz Mahal. Over 20,000 artisans from across Asia participated under the direction of Ustad Ahmad Lahori.',
    architecture: 'An exquisite example of Mughal architecture combining Indo-Islamic, Persian, and Ottoman design. Features symmetrical minarets, central dome, intricate pietra dura inlays, and calligraphy from the Quran.',
    bestVisitingTime: 'October to March (Early sunrise)',
    tags: ['UNESCO', 'Wonder of World', 'Marble', 'Agra', 'Mughal'],
  },
  {
    id: 'qutub-minar',
    name: 'Qutub Minar',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'Heritage',
    unescoStatus: true,
    rating: 4.6,
    entryFee: 35,
    openingTime: '07:00 AM',
    closingTime: '05:00 PM',
    year: 1199,
    builtBy: 'Qutb al-Din Aibak',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?q=80&w=1200&auto=format&fit=crop',
    description: 'A 73-metre high tower of victory, built in 1193 by Qutab-ud-din Aibak immediately after the defeat of Delhi\'s last Hindu kingdom.',
    history: 'Inspired by the Minaret of Jam in Afghanistan, Qutb al-Din Aibak started construction in 1199. It was expanded by Iltutmish and later repaired by Firoz Shah Tughlaq after a lightning strike.',
    architecture: 'Built with red sandstone and marble, decorated with intricate carvings and verses from the Quran. The complex also houses the famous rust-resistant Iron Pillar of Delhi.',
    bestVisitingTime: 'November to February',
    tags: ['UNESCO', 'Tower', 'Delhi', 'Sandstone'],
  },
  {
    id: 'hawa-mahal',
    name: 'Hawa Mahal',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'Palace',
    unescoStatus: true,
    rating: 4.7,
    entryFee: 50,
    openingTime: '09:00 AM',
    closingTime: '05:00 PM',
    year: 1799,
    builtBy: 'Maharaja Sawai Pratap Singh',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?q=80&w=1200&auto=format&fit=crop',
    description: 'The Palace of Breeze constructed from red and pink sandstone with 953 small windows (jharokhas) designed to allow royal ladies to observe street festivals without being seen.',
    history: 'Designed by Lal Chand Ustad for Maharaja Sawai Pratap Singh, grandson of Maharaja Sawai Jai Singh, the founder of Jaipur. Its honeycomb structure allows natural ventilation via the Venturi effect.',
    architecture: 'Five-storey exterior resembling a crown of Lord Krishna, decorated with delicate latticework, dome finials, and vibrant stained glass.',
    bestVisitingTime: 'October to March (Morning)',
    tags: ['Pink City', 'Jaipur', 'Palace', 'Latticework'],
  },
  {
    id: 'red-fort',
    name: 'Red Fort (Lal Qila)',
    city: 'Old Delhi',
    state: 'Delhi',
    category: 'Fort',
    unescoStatus: true,
    rating: 4.5,
    entryFee: 35,
    openingTime: '09:30 AM',
    closingTime: '04:30 PM',
    year: 1648,
    builtBy: 'Emperor Shah Jahan',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=1200&auto=format&fit=crop',
    description: 'The historic fort in the city of Delhi that served as the main residence of the Mughal Emperors for nearly 200 years.',
    history: 'Shah Jahan commissioned construction of the Red Fort on 12 May 1638 when he decided to shift his capital from Agra to Delhi. The fort was completed in 1648.',
    architecture: 'Enclosed by massive octagonal red sandstone walls, featuring Diwan-i-Aam (Hall of Public Audience), Diwan-i-Khas, and Moti Masjid.',
    bestVisitingTime: 'October to March',
    tags: ['UNESCO', 'Fort', 'Delhi', 'Mughal'],
  },
  {
    id: 'konark-sun-temple',
    name: 'Konark Sun Temple',
    city: 'Konark',
    state: 'Odisha',
    category: 'Temple',
    unescoStatus: true,
    rating: 4.8,
    entryFee: 40,
    openingTime: '06:00 AM',
    closingTime: '08:00 PM',
    year: 1250,
    builtBy: 'King Narasimhadeva I',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=1200&auto=format&fit=crop',
    description: 'A 13th-century Sun Temple designed as a monumental chariot with 24 carved stone wheels pulled by seven horses.',
    history: 'Built by King Narasimhadeva I of the Eastern Ganga Dynasty around 1250 CE to commemorate his military victory over invaders.',
    architecture: 'Kalinga architecture style featuring intricately carved stone wheels that function as accurate sundials.',
    bestVisitingTime: 'September to March',
    tags: ['UNESCO', 'Sun Temple', 'Odisha', 'Chariot'],
  },
  {
    id: 'ajanta-caves',
    name: 'Ajanta Caves',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    category: 'Caves',
    unescoStatus: true,
    rating: 4.9,
    entryFee: 40,
    openingTime: '09:00 AM',
    closingTime: '05:00 PM',
    year: -200,
    builtBy: 'Satavahana & Vakataka Dynasties',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-f010e423b971?q=80&w=1200&auto=format&fit=crop',
    description: '30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE featuring world-renowned ancient murals and sculptures.',
    history: 'Discovered accidentally by a British officer, John Smith, in 1819 while hunting tigers. The caves contain masterworks of ancient Indian Buddhist art.',
    architecture: 'Carved directly into a horseshoe-shaped cliff side overlooking the Waghur river, divided into Chaitya halls and Viharas.',
    bestVisitingTime: 'November to March',
    tags: ['UNESCO', 'Caves', 'Paintings', 'Buddhist'],
  },
  {
    id: 'mysore_palace',
    name: 'Mysore Palace',
    city: 'Mysuru',
    state: 'Karnataka',
    category: 'Palace',
    unescoStatus: false,
    rating: 4.7,
    entryFee: 70,
    openingTime: '10:00 AM',
    closingTime: '05:30 PM',
    year: 1912,
    builtBy: 'Krishnaraja Wadiyar IV',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1506461883276-594a12b11cf3?q=80&w=1200&auto=format&fit=crop',
    description: 'The official residence of the Wadiyar dynasty of Mysore, one of the most visited monuments in India after the Taj Mahal.',
    history: 'The present palace was built between 1897 and 1912 by Krishnaraja Wadiyar IV after the previous palace was destroyed by fire. Designed by Henry Irwin in the Indo-Saracenic style.',
    architecture: 'A blend of Indo-Saracenic, Dravidian, Roman and Oriental styles with three-storey stone structure, marble domes, turrets, arches, and golden throne.',
    bestVisitingTime: 'October to February (Dasara festival)',
    tags: ['Palace', 'Karnataka', 'Illuminated', 'Royal'],
  },
  {
    id: 'hampi_ruins',
    name: 'Hampi Group of Monuments',
    city: 'Hampi',
    state: 'Karnataka',
    category: 'Ruins',
    unescoStatus: true,
    rating: 4.8,
    entryFee: 30,
    openingTime: '06:00 AM',
    closingTime: '06:00 PM',
    year: 1336,
    builtBy: 'Vijayanagara Empire',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1590079550810-e63b4e6e10b1?q=80&w=1200&auto=format&fit=crop',
    description: 'The ruins of Vijayanagara, the former capital of the Vijayanagara Empire, spread across 4,100 hectares in the Deccan plateau.',
    history: 'Founded in 1336 CE by Harihara I and Bukka Raya I, Vijayanagara was one of the largest empires of post-classical South Asia until its conquest and sack in 1565.',
    architecture: 'Dravidian style temple complexes, royal enclosures, elephant stables, stepped tanks, and intricate stone sculptures spread across surreal boulder-strewn landscape.',
    bestVisitingTime: 'October to February',
    tags: ['UNESCO', 'Ruins', 'Karnataka', 'Vijayanagara', 'Empire'],
  },
  {
    id: 'gateway_of_india',
    name: 'Gateway of India',
    city: 'Mumbai',
    state: 'Maharashtra',
    category: 'Gateway',
    unescoStatus: false,
    rating: 4.5,
    entryFee: 0,
    openingTime: '24 Hours',
    closingTime: '24 Hours',
    year: 1924,
    builtBy: 'British Colonial Government',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?q=80&w=1200&auto=format&fit=crop',
    description: 'A monumental arch built during the 20th century to commemorate the landing of King George V and Queen Mary at Apollo Bunder in Mumbai.',
    history: 'Designed by architect George Wittet, construction began in 1913 and was completed in 1924. The last British troops left India through the Gateway in 1948.',
    architecture: 'Indo-Saracenic style arch combining Hindu and Muslim architectural elements with basalt structure and yellow Kharodi stone lattice windows.',
    bestVisitingTime: 'November to February',
    tags: ['Mumbai', 'Colonial', 'Arch', 'Harbour', 'Landmark'],
  },
  {
    id: 'amber_fort',
    name: 'Amber Fort',
    city: 'Jaipur',
    state: 'Rajasthan',
    category: 'Fort',
    unescoStatus: true,
    rating: 4.7,
    entryFee: 100,
    openingTime: '08:00 AM',
    closingTime: '05:30 PM',
    year: 1592,
    builtBy: 'Raja Man Singh I',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=1200&auto=format&fit=crop',
    description: 'A majestic fort built with pale yellow and pink sandstone and white marble, perched on a hill with a picturesque lake below.',
    history: 'Built by Raja Man Singh I in 1592 using pale yellow and pink sandstone. It served as the principal residence of the Rajput Maharajas of Amber and Jaipur.',
    architecture: 'A blend of Rajput and Mughal architecture featuring Sheesh Mahal (Mirror Palace) with 1000s of tiny mirrors, Diwan-e-Aam, and intricate floral designs.',
    bestVisitingTime: 'October to March',
    tags: ['UNESCO', 'Fort', 'Jaipur', 'Rajputana', 'Hill Fort'],
  },
  {
    id: 'khajuraho_temples',
    name: 'Khajuraho Group of Monuments',
    city: 'Khajuraho',
    state: 'Madhya Pradesh',
    category: 'Temple',
    unescoStatus: true,
    rating: 4.6,
    entryFee: 40,
    openingTime: '08:00 AM',
    closingTime: '06:00 PM',
    year: 950,
    builtBy: 'Chandela dynasty',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=1200&auto=format&fit=crop',
    description: 'A group of Hindu and Jain temples famous for their Nagara-style architectural symbolism and erotic sculptures.',
    history: 'Built by the Chandela dynasty between 950 and 1050 CE. Originally there were 85 temples of which only 25 survive. Rediscovered by T.S. Burt in 1838.',
    architecture: 'Nagara-style shikhara towers covered in intricate sculptural panels depicting celestial beings, apsaras, and scenes from daily life and mythology.',
    bestVisitingTime: 'October to March',
    tags: ['UNESCO', 'Temple', 'Madhya Pradesh', 'Chandela', 'Sculpture'],
  },
  {
    id: 'ellora_caves',
    name: 'Ellora Caves',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    category: 'Caves',
    unescoStatus: true,
    rating: 4.9,
    entryFee: 40,
    openingTime: '09:00 AM',
    closingTime: '05:30 PM',
    year: 600,
    builtBy: 'Rashtrakuta & Yadava Dynasties',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1567449303183-ae0d6ed1498e?q=80&w=1200&auto=format&fit=crop',
    description: '34 rock-cut caves showcasing the epitome of Indian rock-cut architecture with Buddhist, Hindu, and Jain temples from 6th to 11th century.',
    history: 'Ellora represents three distinct religious groups working side by side – Buddhist, Hindu, and Jain, covering from around 600 CE to 1000 CE. The Kailasa temple is the world\'s largest rock-cut structure.',
    architecture: 'The Kailasa temple (Cave 16), carved out of a single monolithic rock, is the centrepiece — built top to bottom by carving downward, removing an estimated 200,000 tonnes of rock.',
    bestVisitingTime: 'November to March',
    tags: ['UNESCO', 'Caves', 'Maharashtra', 'Kailasa', 'Rock-cut'],
  },
  {
    id: 'meenakshi_temple',
    name: 'Meenakshi Amman Temple',
    city: 'Madurai',
    state: 'Tamil Nadu',
    category: 'Temple',
    unescoStatus: false,
    rating: 4.8,
    entryFee: 0,
    openingTime: '05:00 AM',
    closingTime: '10:00 PM',
    year: 1623,
    builtBy: 'Nayak dynasty',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=1200&auto=format&fit=crop',
    description: 'A historic Hindu temple located on the southern bank of the Vaigai River, with 14 spectacular gateway towers (gopurams) covered in thousands of colourful sculptures.',
    history: 'The existing structure was largely built during the rule of Thirumalai Nayak in 1623-55. The temple is dedicated to Meenakshi, an avatar of Parvati, and her consort Shiva.',
    architecture: 'Dravidian style with 14 multi-coloured ornate gopurams (gateway towers), the tallest reaching 51.9 metres, adorned with thousands of stone figures.',
    bestVisitingTime: 'October to March',
    tags: ['Temple', 'Tamil Nadu', 'Dravidian', 'Gopuram', 'Nayak'],
  },
  {
    id: 'charminar',
    name: 'Charminar',
    city: 'Hyderabad',
    state: 'Telangana',
    category: 'Heritage',
    unescoStatus: false,
    rating: 4.4,
    entryFee: 25,
    openingTime: '09:30 AM',
    closingTime: '05:30 PM',
    year: 1591,
    builtBy: 'Muhammad Quli Qutb Shah',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=1200&auto=format&fit=crop',
    description: 'A monument and mosque built in 1591 at the centre of historic Hyderabad, with four grand arches and four minarets standing 48.7 metres high.',
    history: 'Built by Muhammad Quli Qutb Shah in 1591 to commemorate the eradication of a deadly plague. "Charminar" means Four Minarets in Urdu.',
    architecture: 'Qutb Shahi architecture with Indo-Islamic style, featuring four graceful minarets with balconies and a mosque on the top floor.',
    bestVisitingTime: 'October to February',
    tags: ['Telangana', 'Hyderabad', 'Qutb Shahi', 'Minaret'],
  },
  {
    id: 'brihadeeswarar_temple',
    name: 'Brihadeeswarar Temple',
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    category: 'Temple',
    unescoStatus: true,
    rating: 4.8,
    entryFee: 0,
    openingTime: '06:00 AM',
    closingTime: '08:30 PM',
    year: 1010,
    builtBy: 'Raja Raja Chola I',
    isFeatured: true,
    imageUrl: 'https://images.unsplash.com/photo-1621452773781-0f992fd1f5cb?q=80&w=1200&auto=format&fit=crop',
    description: 'A masterpiece of Dravidian architecture built by Raja Raja Chola I, with a 66-metre vimana (tower) and a massive Nandi bull carved from a single rock.',
    history: 'Completed in 1010 CE during the reign of Chola Emperor Raja Raja I. The temple was built to demonstrate Chola power and devotion to Lord Shiva.',
    architecture: 'Pure Dravidian style — the 66-metre vimana tower casts no shadow at noon on equinox days. The capstone at the top weighs 80 tonnes, raised without any ramp.',
    bestVisitingTime: 'October to March',
    tags: ['UNESCO', 'Temple', 'Tamil Nadu', 'Chola', 'Dravidian'],
  },
  {
    id: 'victoria_memorial',
    name: 'Victoria Memorial',
    city: 'Kolkata',
    state: 'West Bengal',
    category: 'Memorial',
    unescoStatus: false,
    rating: 4.5,
    entryFee: 30,
    openingTime: '10:00 AM',
    closingTime: '05:00 PM',
    year: 1921,
    builtBy: 'British Colonial Government',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?q=80&w=1200&auto=format&fit=crop',
    description: 'A magnificent white marble building built in memory of Queen Victoria. Now a museum housing 25 galleries of colonial-era artefacts and paintings.',
    history: 'Designed by William Emerson and built between 1906 and 1921 by the British raj. It was opened by the Prince of Wales, later King Edward VIII.',
    architecture: 'Indo-Saracenic revivalist style using white Makrana marble from Rajasthan, with elements of Venetian, Egyptian, Deccani, and Mughal architecture.',
    bestVisitingTime: 'October to March',
    tags: ['Kolkata', 'Colonial', 'Marble', 'Museum', 'Victoria'],
  },
  {
    id: 'rani_ki_vav',
    name: 'Rani ki Vav',
    city: 'Patan',
    state: 'Gujarat',
    category: 'Stepwell',
    unescoStatus: true,
    rating: 4.7,
    entryFee: 35,
    openingTime: '08:00 AM',
    closingTime: '06:00 PM',
    year: 1063,
    builtBy: 'Queen Udayamati',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1567416661576-659b10a4f7a3?q=80&w=1200&auto=format&fit=crop',
    description: 'An intricately constructed stepwell built as a memorial to King Bhimdev I, featuring over 500 principal sculptures and 1000 minor ones.',
    history: 'Built by Queen Udayamati in memory of her husband King Bhimdev I around 1063 CE. It was submerged and silted over for centuries before being excavated in the 1980s.',
    architecture: 'A seven-storey inverted temple structure with intricate carvings dedicated to Vishnu on three walls. The walls are covered with Apsaras applying makeup.',
    bestVisitingTime: 'October to March',
    tags: ['UNESCO', 'Stepwell', 'Gujarat', 'Solanki', 'Sculpture'],
  },
  {
    id: 'sanchi_stupa',
    name: 'Sanchi Stupa',
    city: 'Sanchi',
    state: 'Madhya Pradesh',
    category: 'Buddhist',
    unescoStatus: true,
    rating: 4.5,
    entryFee: 40,
    openingTime: '08:30 AM',
    closingTime: '05:30 PM',
    year: -300,
    builtBy: 'Emperor Ashoka',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1533282960533-51328aa49826?q=80&w=1200&auto=format&fit=crop',
    description: 'The oldest stone structure in India and one of the most well-preserved stupas, built by Emperor Ashoka to enshrine Buddhist relics.',
    history: 'Originally commissioned by Emperor Ashoka the Great in the 3rd century BCE. It was later expanded by the Satavahana and other dynasties up to the 12th century CE.',
    architecture: 'A hemispherical dome (anda) housing relics, surrounded by a railing (vedika) and four ornately carved stone gateways (toranas) depicting Jataka tales.',
    bestVisitingTime: 'November to March',
    tags: ['UNESCO', 'Buddhist', 'Madhya Pradesh', 'Ashoka', 'Stupa'],
  },
  {
    id: 'lotus_temple',
    name: 'Lotus Temple',
    city: 'New Delhi',
    state: 'Delhi',
    category: 'Modern',
    unescoStatus: false,
    rating: 4.6,
    entryFee: 0,
    openingTime: '09:00 AM',
    closingTime: '05:30 PM',
    year: 1986,
    builtBy: 'Fariborz Sahba',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1555921015-5532091f6026?q=80&w=1200&auto=format&fit=crop',
    description: 'A Bahai House of Worship known for its flowerlike shape consisting of 27 free-standing marble-clad petals arranged in clusters of three.',
    history: 'Designed by Iranian-Canadian architect Fariborz Sahba and completed in 1986. It has received more visitors than the Eiffel Tower since opening.',
    architecture: '27 free-standing marble-clad petals arranged in clusters of three to form nine sides. The main hall has a height of 34.27 metres, capable of seating 1300 people.',
    bestVisitingTime: 'October to March',
    tags: ['Delhi', 'Bahai', 'Lotus', 'Modern', 'Marble'],
  },
  {
    id: 'jaisalmer_fort',
    name: 'Jaisalmer Fort',
    city: 'Jaisalmer',
    state: 'Rajasthan',
    category: 'Fort',
    unescoStatus: true,
    rating: 4.7,
    entryFee: 50,
    openingTime: '09:00 AM',
    closingTime: '06:00 PM',
    year: 1156,
    builtBy: 'Rawal Jaisal',
    isFeatured: false,
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed68b6b?q=80&w=1200&auto=format&fit=crop',
    description: 'One of the very few living forts in the world, where nearly one-fourth of the old city population still resides within the fort walls.',
    history: 'Built in 1156 CE by Rajput ruler Rawal Jaisal. The fort sits on Trikuta Hill and was the centre of significant trade routes along the ancient Silk Road.',
    architecture: 'Rajput architecture featuring 99 bastions with massive golden yellow sandstone walls that seem to grow out of the desert. Known as the Golden Fort (Sonar Quila).',
    bestVisitingTime: 'October to March (Desert festival)',
    tags: ['UNESCO', 'Fort', 'Rajasthan', 'Living Fort', 'Golden'],
  },
];

async function seed() {
  console.log(`\n🌱  Seeding ${MONUMENTS.length} monuments to Firestore...\n`);

  let success = 0;
  let failed  = 0;

  for (const monument of MONUMENTS) {
    const { id, ...data } = monument;
    try {
      await db.collection('monuments').doc(id).set(data, { merge: true });
      console.log(`  ✅  ${monument.name}`);
      success++;
    } catch (err) {
      console.error(`  ❌  ${monument.name}: ${err.message}`);
      failed++;
    }
  }

  console.log(`\n🎉  Done! ${success} uploaded, ${failed} failed.\n`);
  console.log('💡  Next steps:');
  console.log('   1. Go to Firebase Console → Firestore → Enable "monuments" index on "rating DESC"');
  console.log('   2. Run "npm run dev" to start the web app\n');

  process.exit(0);
}

seed().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
